version: '2'
services:
  rails:
    image: ph-rails
    build: .
    command: ./entrypoint.sh
    env_file: .env
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    volumes_from:
      - bundle
    depends_on:
      - db
  bundle:
    image: ph-rails
    command: echo "I'm a little data container"
    volumes:
      - /bundle
  db:
    image: mysql:5.7.17
    volumes:
      - ./db_data:/var/lib/mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=ph-dev
